parameters: ~
services:
  jigoshop.admin.migration.options:
    class: Jigoshop\Admin\Migration\Options
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.tax'
    tags:
      - { name: jigoshop.admin.migration }
  jigoshop.admin.migration.coupons:
    class: Jigoshop\Admin\Migration\Coupons
    arguments:
      - '@wpal'
      - '@jigoshop.options'
    tags:
      - { name: jigoshop.admin.migration }
  jigoshop.admin.migration.emails:
    class: Jigoshop\Admin\Migration\Emails
    arguments:
      - '@wpal'
      - '@jigoshop.options'
    tags:
      - { name: jigoshop.admin.migration }
  jigoshop.admin.migration.products:
    class: Jigoshop\Admin\Migration\Products
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.product'
    tags:
      - { name: jigoshop.admin.migration }
  jigoshop.admin.migration.orders:
    class: Jigoshop\Admin\Migration\Orders
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.messages'
      - '@jigoshop.service.order'
      - '@jigoshop.service.shipping'
      - '@jigoshop.service.payment'
      - '@jigoshop.service.product'
    tags:
      - { name: jigoshop.admin.migration }
