parameters: ~
services:
  jigoshop.admin.page_resolver:
    class: Jigoshop\Admin\PageResolver
    arguments:
      - '@wpal'
  jigoshop.admin.page.orders:
    class: Jigoshop\Admin\Page\Orders
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.order'
      - '@jigoshop.service.tax'
      - '@jigoshop.helper.styles'
      - '@jigoshop.helper.scripts'
  jigoshop.admin.page.order:
    class: Jigoshop\Admin\Page\Order
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.order'
      - '@jigoshop.service.product'
      - '@jigoshop.service.customer'
      - '@jigoshop.service.shipping'
      - '@jigoshop.service.tax'
      - '@jigoshop.helper.styles'
      - '@jigoshop.helper.scripts'
  jigoshop.admin.page.products:
    class: Jigoshop\Admin\Page\Products
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.post_type.product'
      - '@jigoshop.service.product'
      - '@jigoshop.helper.styles'
      - '@jigoshop.helper.scripts'
  jigoshop.admin.page.product:
    class: Jigoshop\Admin\Page\Product
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.post_type.product'
      - '@jigoshop.service.product'
      - '@jigoshop.helper.styles'
      - '@jigoshop.helper.scripts'
  jigoshop.admin.page.email:
    class: Jigoshop\Admin\Page\Email
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.email'
      - '@jigoshop.helper.styles'
      - '@jigoshop.helper.scripts'
  jigoshop.admin.page.coupon:
    class: Jigoshop\Admin\Page\Coupon
    arguments:
      - '@wpal'
      - '@jigoshop.options'
      - '@jigoshop.service.coupon'
      - '@jigoshop.service.payment'
      - '@jigoshop.helper.styles'
      - '@jigoshop.helper.scripts'
